/* Autogenerated file. Do not edit manually. */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */

import * as Circuits from ".";

declare module "hardhat/types/runtime" {
  interface HardhatZKit {
    getCircuit(name: "BurnCircuit"): Promise<Circuits.BurnCircuit>;
    getCircuit(name: "MintCircuit"): Promise<Circuits.MintCircuit>;
    getCircuit(
      name: "RegistrationCircuit",
    ): Promise<Circuits.RegistrationCircuit>;
    getCircuit(name: "TransferCircuit"): Promise<Circuits.TransferCircuit>;
    getCircuit(name: "WithdrawCircuit"): Promise<Circuits.WithdrawCircuit>;
  }
}
